#The name of the mines
World-Name: mines
#How many blocks each mine should be apart from the other. This must be at least the radius of the mine schematic (distance from the center to the edge) or the mines will overlap
Mine-Distance: 150
#the schematic name for the mine. this file must exist or bad things will happen!
Schematic-Name: mine.schematic

#This maps different block types to different locations in the schematic
Blocks:
  #Defines where the players will initially spawn. This can be changed by players
  Spawnpoint: BEACON
  #Defines a corner of the mining area. Place this at both corners. They will be replaced with air and the mine will be filled
  Mine-Corner: POWERED_RAIL
  Sell-NPC: WOOL

#The default block for mines
Default-Block: REDSTONE_BLOCK

#Options for types of block a mine can be made of
Block-Options:
  - REDSTONE_BLOCK
  - EMERALD_BLOCK
  - DIAMOND_BLOCK
  - GOLD_BLOCK

#Name for the Sell NPC
NPC-Name: Merchant
NPC-Skin: TraderNPC

#Default percentage in tax that mine owners will be given
Tax-Percentage: 5

#Color Customisation for messages
Colors:
  INFO: GOLD
  SYNTAX: AQUA
  ERROR: RED
  HELP: DARK_BLUE
